# yaml-language-server: $schema=../../codegenerator/cli/npm/envio/evm.schema.json
name: test_codegen
description: Gravatar for Ethereum
rollback_on_reorg: true
save_full_history: false
field_selection:
  transaction_fields:
    - transactionIndex
    - hash
contracts:
  - name: Noop
    handler: ./src/EventHandlers.res.js
    events:
      - event: "EmptyEvent()"
  - name: EventFiltersTest
    handler: ./src/EventHandlers.res.js
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 amount)
      - event: WildcardWithAddress(address indexed from, address indexed to, uint256 amount)
      - event: WithExcessField(address indexed from)
      - event: EmptyFiltersArray(address indexed from)
networks:
  - id: 1337
    rpc_config:
      url: http://localhost:8545 # RPC URL that will be used to subscribe to blockchain data on this network
      initial_block_interval: 10000
      backoff_multiplicative: 0.8
      acceleration_additive: 2000
      interval_ceiling: 10000
      backoff_millis: 5000
      query_timeout_millis: 20000
    start_block: 1
    contracts:
      - name: Gravatar
        abi_file_path: abis/gravatar-abi.json
        address: "0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"
        handler: ./src/EventHandlers.res.js
        start_block: 500 # Test specific start block for Gravatar
        events:
          - event: "CustomSelection()"
            field_selection:
              block_fields:
                - parentHash
              transaction_fields:
                - to
                - from
                - hash
          - event: "EmptyEvent()"
          - event: "TestEventWithLongNameBeyondThePostgresEnumCharacterLimit(address testField)"
          - event: "TestEventThatCopiesBigIntViaLinkedEntities(string param_that_should_be_removed_when_issue_1026_is_fixed)"
          - event: "TestEventWithReservedKeyword(string module)"
          - event: "TestEvent"
          - event: "TestEvent()"
            name: "TestEventWithCustomName"
          - event: "NewGravatar"
          - event: "UpdatedGravatar"
          - event: "FactoryEvent(address indexed contract, string testCase)"
      - name: NftFactory
        abi_file_path: abis/NftFactory.json
        address: "0xa2F6E6029638cCb484A2ccb6414499aD3e825CaC"
        handler: src/EventHandlers.ts
        start_block: 1000 # Test different start block for NftFactory
        events:
          - event: "SimpleNftCreated"
      - name: SimpleNft
        abi_file_path: abis/SimpleNft.json
        handler: src/EventHandlers.ts
        # No start_block specified - should use network default (1)
        events:
          - event: "Erc20Transfer(address indexed from, address indexed to, uint256 amount)"
          - event: "Transfer"
      - name: TestEvents
        abi_file_path: ./contracts/artifacts/contracts/TestEvents.sol/TestEvents.json
        handler: src/EventHandlers.ts
        start_block: 2000 # Test another different start block for TestEvents
        events:
          - event: "IndexedUint"
          - event: "IndexedInt"
          - event: "IndexedAddress"
          - event: "IndexedBool"
          - event: "IndexedBytes"
          - event: "IndexedString"
          - event: "IndexedFixedBytes"
          - event: "IndexedStruct"
          - event: "IndexedArray"
          - event: "IndexedFixedArray"
          - event: "IndexedNestedArray"
          - event: "IndexedStructArray"
          - event: "IndexedNestedStruct"
          - event: "IndexedStructWithArray"
  - id: 1
    start_block: 1
    contracts:
      - name: Noop
        address: "0x0B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"
        start_block: 100 # Test start block for Noop on chain 1
  - id: 100
    start_block: 1
    contracts:
      - name: EventFiltersTest
        start_block: 50 # Test start block for EventFiltersTest
  - id: 137
    start_block: 1
    contracts:
      - name: EventFiltersTest
        # No start_block - should use network default (1)
      - name: Noop
        address: "0x0B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"
        start_block: 200 # Test start block for Noop on chain 137
raw_events: true
